### ISSUE TITLE
不兼容 Yii 2.0.16 版本

### ISSUE THREAD

**Issue by takashiki** [lichunqiang/yii2-ajaxform#2]
2.0.16 修改了 `ActiveForm::run()` 方法，改成了有返回值的，所以到这个版本就不兼容了。

见 https://github.com/yiisoft/yii2/blob/2.0.16/framework/CHANGELOG.md

**Comment by lichunqiang** [comment]
Released [1.0.3](https://github.com/lichunqiang/yii2-ajaxform/releases/tag/1.0.3)
